swagger: "2.0"
info:
  version: "1.0.0"
  title: Banking API
host: localhost:8080
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /students:
    get:
      description: Get a list of students from the database
      summary: Get students
      operationId: GetStudents
      parameters:
        - name: all
          in: query
          description: students
          type: string

